### ISSUE TITLE
Add an option to disable paper-dialog backdrop

### ISSUE THREAD

**Issue by cforgeard** [Dabolus/share-menu#1]
Can you add an option to disable paper-dialog backdrop ?

**Comment by Dabolus** [comment]
Great idea! Going to add it in a couple of hours.

**Comment by Dabolus** [comment]
Added with https://github.com/Dabolus/share-menu/commit/e0ddbe5d321fbcc1ed843f2ca81e4b4c451e4beb, going to draft a new release soon
