### ISSUE TITLE
Uncaught ReferenceError: shareMenu is not defined

### ISSUE THREAD

**Issue by a-haan** [Dabolus/share-menu#4]
Hi,

I've imported this component into my project with 

`<link rel="import" href="../bower_components/share-menu/share-menu.html">`

and use the demo code

 `<share-menu id="shareMenu" title="Ohai!" text="Just a test" url="https://www.example.com/"></share-menu>
<button onclick="shareMenu.share()">Share!</button>`

I get console error:
**Uncaught ReferenceError: shareMenu is not defined
    at HTMLElement.onclick**

**Comment by Dabolus** [comment]
Are you using it inside another Polymer element?

**Comment by a-haan** [comment]
I've tried inside and outside polymer elements with the same issue

**Comment by a-haan** [comment]
Looks like Lazyloading is a no no, I've directly imported it into index and all is working - Thank you so much!

**Comment by pranavyadavGOT** [comment]
@a-haan 

Can you please elaborate on your solution?

I have the same error.

**Comment by Dabolus** [comment]
@pranavyadavGOT can you please provide some context? The solution depends on how you're trying to use the element

**Comment by pranavyadavGOT** [comment]
@Dabolus 

I am trying to allow users on my app to share content to their social media.  The "share-menu" component is located inside another component and I am working on Polymer 2. 

I am trying to run the demo example, however, the "shareMenu is not defined" error is shown.

**Comment by Dabolus** [comment]
@pranavyadavGOT the demo only works in a light DOM environment (i.e. it basically does `document.getElementById('shareMenu')` to get the reference to the share menu element). However, this won't work in the shadow DOM. If you're using the share menu in another Polymer 2 element, you should access the share menu using `this.$.id`. For example, if your share menu element looks like this:
```html
<share-menu id="shareMenu" title="Ohai!" text="Just a test" url="https://www.example.com/"></share-menu>
```
You should be able to get access to it using `this.$.shareMenu`.

**Comment by pranavyadavGOT** [comment]
@Dabolus 

I have tried this method, however, it results in this error: "share is not a function".
The only thing I changed from your example is the URL.

![image](https://user-images.githubusercontent.com/39270306/50239329-e513d680-038f-11e9-9824-945ce8ce2ba5.png)

![image](https://user-images.githubusercontent.com/39270306/50239345-ee9d3e80-038f-11e9-97d5-48dd0f117eba.png)

![image](https://user-images.githubusercontent.com/39270306/50239361-f65ce300-038f-11e9-84b8-aa4527a15a67.png)

**Comment by a-haan** [comment]
@pranavyadavGOT Hi, the only way I got it to work for me was by putting

`  <share-menu id="shareMenu" via="ahaan20" dialog-title="Share now!" copy-success-text="Text copied to clipboard!" copy-failed-text="Oh no! Couldn't copy the text automatically :(" is-image="auto"></share-menu>`

into my index.html and in one of my elements I put 

` <paper-fab noink icon="share" title="share" onclick="shareMenu.share()"></paper-fab>`

this did what I wanted, but I have trouble with sharing multiple pages.  
If I shared one page and then tried to share another, it would share the metadata from the first page I shared.

I was hoping the new share-menu build wouldn't have that issue but I haven't tried it yet.

**Comment by pranavyadavGOT** [comment]
@a-haan @Dabolus 

Which version are you using: npm or bower? Does this matter?

**Comment by pranavyadavGOT** [comment]
@a-haan 

I have tried your solution, however, 'paper-fab' is a Polymer 3 component (I am using Polymer 2).
I have tried it with a 'paper-button' instead and the error is still the same.

One thing I noticed was that you do not include a URL in your 'share-menu' component, was this intentional?

**Comment by a-haan** [comment]
@pranavyadavGOT I'm using Bower with Polymer 2, it shouldn't matter what element you put 
`onclick="shareMenu.share()"` into, it should work the same way.

My import tag is on the same component as the share menu button but as long as its imported somewhere it should be fine.

`<link rel="import" href="../bower_components/share-menu/share-menu.html">`

I left out the URL so the URL is grabbed from `window.location.href` - I may be using an older version to you also.   "version": "2.0.4",

**Comment by pranavyadavGOT** [comment]
@a-haan 

I have installed the component using the bower command  "bower install --save Dabolus/share-menu".

One thing I noticed, is that your reference `<link rel="import" href="../bower_components/share-menu/share-menu.html">` is to "share-menu.html".

Mine is to:
![image](https://user-images.githubusercontent.com/39270306/50245528-be11d080-03a0-11e9-879a-f58728fffafb.png)
"index.html" and "share-menu.ts"

This is what "index.html" contains:
![image](https://user-images.githubusercontent.com/39270306/50245586-e00b5300-03a0-11e9-9f0b-da0191f01811.png)

I have referenced it just to make sure that I don't have any loose ends.

**Comment by Dabolus** [comment]
@pranavyadavGOT your issue is that by installing the element using that command you are actually installing the latest version of the element from the master branch. However, the latest version of the element is not compatible with Bower anymore. You have to specify the latest Bower version of the element to install it correctly (my bad for not specifying it in the readme):
```bash
$ bower install --save Dabolus/share-menu#2.0.4
```
After that, you should be able to use the element in the same way as @a-haan explained.

As a side-note, I just released version `3.0.1` of the element that should also work [in a non-module environment](https://github.com/Dabolus/share-menu#without-npmyarn). Version 3.x is much lighter as it has no dependencies at all, so you might want to give it a try.

**Comment by pranavyadavGOT** [comment]
@a-haan @Dabolus 

Awesome, that made it work! 

Notable issue:
- unable to see the social icons
- facebook sending error (with or without specifying URL and with or without specifying app-id)
![image](https://user-images.githubusercontent.com/39270306/50250388-99245a00-03ae-11e9-912c-c052fc8fb9d5.png)

**Comment by pranavyadavGOT** [comment]
@Dabolus 

Any updates on these issues?

**Comment by Dabolus** [comment]
@pranavyadavGOT sorry but I completely forgot about them since this is a closed issue. I would suggest to open a new issue for each of them so that I can keep track of them more easily.

**Comment by pranavyadavGOT** [comment]
`<script src="https://unpkg.com/share-menu/share-menu.iife.min.js"></script>`

This version seems to have solved both problems. Thank you!
